import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import ConvexClientProvider from "./ConvexClientProvider";
import Navbar from "./components/Navbar";
import { Separator } from "@/components/ui/separator"
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ConvexClientProvider>
            <div className="flex justify-center">

            <Navbar/>
              
            </div>
            <div className="flex justify-center">

            <Separator className="max-w-lg"/>
            </div>
            {children}
            <Toaster />
            </ConvexClientProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
